version: '3'

services: # consumer container
  node1:
    env_file:
      - .env
    image: ${IMAGES}:${TIMESTAMP}-${ENV}
    ports:
      - "20300:6363/tcp" # ndn 1
      - "20300:6363/udp"
      - "20302:8080/tcp" # ndn http
    working_dir: /usr/src/app
    networks:
      - node_network

  node2:
    env_file:
      - .env
    image: ${IMAGES}:${TIMESTAMP}-${ENV}
    ports:
      - "20304:6363/tcp" # ndn 1
      - "20304:6363/udp"
      - "20306:8080/tcp" # ndn http
    working_dir: /usr/src/app
    networks:
      - node_network

networks:
  node_network:
    driver: bridge