version: '3'

services: # consumer container
  node1:
    image: cpd9957/named-data-networking:2022.09-none
    ports:
      - "20300:6363/tcp" # ndn 1
      - "20300:6363/udp"
      - "20302:8080/tcp" # ndn http
    volumes:
      - ./shared/src/node1:/usr/src/app/node1
    networks:
      - node_network

  node2:
    image: cpd9957/named-data-networking:2022.09-none
    ports:
      - "20304:6363/tcp" # ndn 1
      - "20304:6363/udp"
      - "20306:8080/tcp" # ndn http
    volumes:
      - ./shared/src/node2:/usr/src/app/node2
    networks:
      - node_network

#  node_mgnt:
#    image: python3.8-buster
#    environment:
#      - ""
#    ports:
#      - "20220:20020"
#    working_dir: /usr/src/app
#    volumes:
#      - ""
#    networks:
#      - node_network



networks:
  node_network:
    driver: bridge